import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Header";
import Footer from "./Footer";



export const metadata: Metadata = {
  title: "nextjs-tailwindcss-udemy-blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head />
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <Header />
        {children}
        <Footer />
      </body>
    </html >
  );
}
